Traceback (most recent call last):
  File "/opt/ros/humble/share/rosidl_generator_c/cmake/../../../lib/rosidl_generator_c/rosidl_generator_c", line 38, in <module>
    sys.exit(main())
  File "/opt/ros/humble/share/rosidl_generator_c/cmake/../../../lib/rosidl_generator_c/rosidl_generator_c", line 34, in main
    generate_c(args.generator_arguments_file)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_generator_c/__init__.py", line 37, in generate_c
    return generate_files(
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_cmake/__init__.py", line 55, in generate_files
    args = read_generator_arguments(generator_arguments_file)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_cmake/__init__.py", line 39, in read_generator_arguments
    return json.load(h)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 85 column 1 (char 6060)
gmake[2]: *** [CMakeFiles/ros2_pkg__rosidl_generator_c.dir/build.make:183: rosidl_generator_c/ros2_pkg/srv/odd_even_check.h] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:232: CMakeFiles/ros2_pkg__rosidl_generator_c.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
